language: android

env:
  global:
    - ADB_INSTALL_TIMEOUT=5

android:
  components:
    - tools
    - platform-tools

jdk:
  - oraclejdk8
before_install:

  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"

licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

install: ./cmds/ci/install.sh

before_script: ./cmds/ci/before_script.sh

script: ./cmds/ci/run_test.sh

after_success: ./cmds/ci/after_success.sh

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle
    - $HOME/.android/build-cache